export const PricingPlans = [
  {
    id: "free",
    name: "Free",
    description: "Perfect for small teams and individual developers.",
    monthlyPrice: 0,
    yearlyPrice: 0,
    projectLimit: 3,
    documentLimit: 5,
    researchLimit: 3,
    employeeLimit: 5,
    features: [
      "Up to 5 team members",
      "3 projects/month",
      "5 documents/month",
      "AI-Generated Documentation",
      "Basic Task Assignment",
      "Email support",
      "3 AI Research Requests/day",
    ],
    popular: false,
  },
  {
    id: "pro",
    name: "Professional",
    description: "Ideal for growing development teams with multiple projects.",
    monthlyPrice: 79,
    yearlyPrice: 790,
    projectLimit: 3,
    documentLimit: 5,
    researchLimit: 3,
    employeeLimit: 5,
    features: [
      "Unlimited team members",
      "Unlimited projects",
      "Unlimited documents",
      "Everything in Professional",
      "Dedicated account manager",
      "24/7 phone & email support",
      "Advanced analytics & reporting",
      "Unlimited research",
    ],
    popular: true,
  },
];
